_LICENSE=LGPL3 GPLv2
_LICENSE_COMB=dual
_LICENSE_NAME=Dual (any of): LGPL3 GPLv2
_LICENSE_PERMS=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS=
_LICENSE_NAME_LGPL3=GNU Lesser General Public License version 3
_LICENSE_PERMS_LGPL3=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_LGPL3=FSF GPL OSI
_LICENSE_DISTFILES_LGPL3=npth-1.2.tar.bz2
_LICENSE_NAME_GPLv2=GNU General Public License version 2
_LICENSE_PERMS_GPLv2=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_GPLv2=FSF GPL OSI
_LICENSE_DISTFILES_GPLv2=npth-1.2.tar.bz2
