#!/bin/sh
#
# $FreeBSD: branches/2016Q1/net/mDNSResponder/files/mdnsd.in 340872 2014-01-24 00:14:07Z mat $

# PROVIDE: mdnsd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=mdnsd
rcvar=mdnsd_enable

load_rc_config $name

: ${mdnsd_enable="NO"}
: ${mdnsd_pidfile="/var/run/${name}.pid"}

command="/usr/local/sbin/${name}"
pidfile="${mdnsd_pidfile}"

run_rc_command $*
