_LICENSE=GPLv3 LGPL3
_LICENSE_COMB=multi
_LICENSE_NAME=Multiple (all of): GPLv3 LGPL3
_LICENSE_PERMS=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS=
_LICENSE_NAME_GPLv3=GNU General Public License version 3
_LICENSE_PERMS_GPLv3=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_GPLv3=FSF GPL OSI
_LICENSE_DISTFILES_GPLv3=gnupg-2.1.8.tar.bz2 gnupg-2.1.8.tar.bz2.sig
_LICENSE_NAME_LGPL3=GNU Lesser General Public License version 3
_LICENSE_PERMS_LGPL3=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_LGPL3=FSF GPL OSI
_LICENSE_DISTFILES_LGPL3=gnupg-2.1.8.tar.bz2 gnupg-2.1.8.tar.bz2.sig
